server:
  port: 8081

spring:
  application:
    name: product-service
  security:
    oauth2:
      resourceserver:
        jwt:
          # In K8s, this will be the internal URL of your Identity Provider
          issuer-uri: ${AUTH_ISSUER_URI:http://localhost:9000/realms/vmc-realm}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true